### PR TITLE
[#191] Fix tab zaakobjecttype

### LINKED ISSUE #191: Als gebruiker wil ik Objecttypen kunnen zien en bewerken
anderObjecttype: Must be a valid boolean.
objecttype: Voer een geldige URL in.
relatieOmschrijving: Dit veld is verplicht.

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #191 

Based on https://github.com/maykinmedia/open-beheer/pull/205

### CODE REVIEW

File: frontend/src/pages/zaaktype/tabs/objecttypen.tsx [hunk 1]
```diff
@@ -6,23 +6,39 @@ export const TABS_CONFIG_OBJECTTYPEN: TabConfig<TargetType> = {
...
       expandFields: [
-        "objecttype",
-        "anderObjecttype",
-        "beginObject",
-        "eindeObject",
+        {
+          name: "objecttype",
+          type: "string",
+          // @ts-expect-error - FIXME: Extending TypedField here.
+          initValue: () => undefined,
```
Comment (SilviaAmAm) [inline frontend/src/pages/zaaktype/tabs/objecttypen.tsx:13]: I did this so that the defaults are handled by the backend for now, since I am not sure what the frontend changes will be to make this look to the `_expand.zaakobjecttypen.objecttype` field which contains the options.

**Review by CharString — APPROVED** [review]
@SilviaAmAm We're having isolation issues with the cassettes: depending on running order, the _cached requests will end up in different cassettes. I work around it by running them in `new_episodes` mode so it doesn't fail when I run a single test that happens not have a _cached request in it's cassette, which is fine, but not ideal. I'll be having some shower/running thoughts over this.
